// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.30.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ProtocolAttributesIdentifierPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifierPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ProtocolDeviceFeaturesPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeaturesPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ProtocolAttributesIdentifier
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
          dynamic raw);

  @protected
  ProtocolDeviceFeatures
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          dynamic raw);

  @protected
  Map<ProtocolAttributesIdentifier, ProtocolDeviceFeatures>
      dco_decode_Map_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          dynamic raw);

  @protected
  ProtocolAttributesIdentifier
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
          dynamic raw);

  @protected
  ProtocolDeviceFeatures
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  EngineOptionsExternal dco_decode_box_autoadd_engine_options_external(
      dynamic raw);

  @protected
  ExposedUserConfig dco_decode_box_autoadd_exposed_user_config(dynamic raw);

  @protected
  ExposedWebsocketSpecifier dco_decode_box_autoadd_exposed_websocket_specifier(
      dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  EngineOptionsExternal dco_decode_engine_options_external(dynamic raw);

  @protected
  ExposedUserConfig dco_decode_exposed_user_config(dynamic raw);

  @protected
  ExposedUserDeviceConfig dco_decode_exposed_user_device_config(dynamic raw);

  @protected
  ExposedUserDeviceSpecifiers dco_decode_exposed_user_device_specifiers(
      dynamic raw);

  @protected
  ExposedWebsocketSpecifier dco_decode_exposed_websocket_specifier(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ExposedUserDeviceConfig> dco_decode_list_exposed_user_device_config(
      dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(ProtocolAttributesIdentifier, ProtocolDeviceFeatures)>
      dco_decode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_attributes_identifier_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_device_features(
          dynamic raw);

  @protected
  List<(String, ExposedUserDeviceSpecifiers)>
      dco_decode_list_record_string_exposed_user_device_specifiers(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ExposedWebsocketSpecifier?
      dco_decode_opt_box_autoadd_exposed_websocket_specifier(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  (
    ProtocolAttributesIdentifier,
    ProtocolDeviceFeatures
  ) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_attributes_identifier_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_device_features(
      dynamic raw);

  @protected
  (String, ExposedUserDeviceSpecifiers)
      dco_decode_record_string_exposed_user_device_specifiers(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserConfigDeviceIdentifier dco_decode_user_config_device_identifier(
      dynamic raw);

  @protected
  int dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ProtocolAttributesIdentifier
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
          SseDeserializer deserializer);

  @protected
  ProtocolDeviceFeatures
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          SseDeserializer deserializer);

  @protected
  Map<ProtocolAttributesIdentifier, ProtocolDeviceFeatures>
      sse_decode_Map_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          SseDeserializer deserializer);

  @protected
  ProtocolAttributesIdentifier
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
          SseDeserializer deserializer);

  @protected
  ProtocolDeviceFeatures
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EngineOptionsExternal sse_decode_box_autoadd_engine_options_external(
      SseDeserializer deserializer);

  @protected
  ExposedUserConfig sse_decode_box_autoadd_exposed_user_config(
      SseDeserializer deserializer);

  @protected
  ExposedWebsocketSpecifier sse_decode_box_autoadd_exposed_websocket_specifier(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  EngineOptionsExternal sse_decode_engine_options_external(
      SseDeserializer deserializer);

  @protected
  ExposedUserConfig sse_decode_exposed_user_config(
      SseDeserializer deserializer);

  @protected
  ExposedUserDeviceConfig sse_decode_exposed_user_device_config(
      SseDeserializer deserializer);

  @protected
  ExposedUserDeviceSpecifiers sse_decode_exposed_user_device_specifiers(
      SseDeserializer deserializer);

  @protected
  ExposedWebsocketSpecifier sse_decode_exposed_websocket_specifier(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ExposedUserDeviceConfig> sse_decode_list_exposed_user_device_config(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(ProtocolAttributesIdentifier, ProtocolDeviceFeatures)>
      sse_decode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_attributes_identifier_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_device_features(
          SseDeserializer deserializer);

  @protected
  List<(String, ExposedUserDeviceSpecifiers)>
      sse_decode_list_record_string_exposed_user_device_specifiers(
          SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ExposedWebsocketSpecifier?
      sse_decode_opt_box_autoadd_exposed_websocket_specifier(
          SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  (
    ProtocolAttributesIdentifier,
    ProtocolDeviceFeatures
  ) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_attributes_identifier_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_device_features(
      SseDeserializer deserializer);

  @protected
  (String, ExposedUserDeviceSpecifiers)
      sse_decode_record_string_exposed_user_device_specifiers(
          SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserConfigDeviceIdentifier sse_decode_user_config_device_identifier(
      SseDeserializer deserializer);

  @protected
  int sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
          ProtocolAttributesIdentifier self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          ProtocolDeviceFeatures self, SseSerializer serializer);

  @protected
  void
      sse_encode_Map_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          Map<ProtocolAttributesIdentifier, ProtocolDeviceFeatures> self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
          ProtocolAttributesIdentifier self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
          ProtocolDeviceFeatures self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_engine_options_external(
      EngineOptionsExternal self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_exposed_user_config(
      ExposedUserConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_exposed_websocket_specifier(
      ExposedWebsocketSpecifier self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_engine_options_external(
      EngineOptionsExternal self, SseSerializer serializer);

  @protected
  void sse_encode_exposed_user_config(
      ExposedUserConfig self, SseSerializer serializer);

  @protected
  void sse_encode_exposed_user_device_config(
      ExposedUserDeviceConfig self, SseSerializer serializer);

  @protected
  void sse_encode_exposed_user_device_specifiers(
      ExposedUserDeviceSpecifiers self, SseSerializer serializer);

  @protected
  void sse_encode_exposed_websocket_specifier(
      ExposedWebsocketSpecifier self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_exposed_user_device_config(
      List<ExposedUserDeviceConfig> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_attributes_identifier_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_device_features(
          List<(ProtocolAttributesIdentifier, ProtocolDeviceFeatures)> self,
          SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_exposed_user_device_specifiers(
      List<(String, ExposedUserDeviceSpecifiers)> self,
      SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_exposed_websocket_specifier(
      ExposedWebsocketSpecifier? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void
      sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_attributes_identifier_auto_owned_rust_opaque_flutter_rust_bridgefor_generatedrust_async_rw_lock_protocol_device_features(
          (ProtocolAttributesIdentifier, ProtocolDeviceFeatures) self,
          SseSerializer serializer);

  @protected
  void sse_encode_record_string_exposed_user_device_specifiers(
      (String, ExposedUserDeviceSpecifiers) self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_config_device_identifier(
      UserConfigDeviceIdentifier self, SseSerializer serializer);

  @protected
  void sse_encode_usize(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifierPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_intiface_central_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifierPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifierPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_intiface_central_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifier =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolAttributesIdentifierPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeaturesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_intiface_central_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeaturesPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeaturesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_intiface_central_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeatures =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedrust_asyncRwLockProtocolDeviceFeaturesPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
