name: Intiface Central Build

# Only build on tag pushes
on: 
  push:
#    branches:
#      - main
#      - dev
#      - ci
    tags:
      - 'v*'      

concurrency:
  group: ${{ github.head_ref ||  github.ref }}
  cancel-in-progress: true      
            
jobs:
  linux:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./intiface-central

    steps:
      - uses: actions/checkout@v3
        with:
          repository: buttplugio/buttplug
          path: buttplug
      - uses: actions/checkout@v3
        with:
          repository: buttplugio/buttplug_dart
          path: buttplug_dart
      - uses: actions/checkout@v3
        with:
          path: intiface-central

      - name: rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: |
         sudo apt-get update -y
         sudo apt-get install -y ninja-build libudev-dev libgtk-3-dev libcurl4-openssl-dev
      - run: flutter config --enable-linux-desktop
        name: flutter config
      - run: flutter build linux --release --dart-define="SENTRY_DSN=${{ secrets.SENTRY_DSN }}" --dart-define="DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}"
        name: flutter build
      - name: Zip Release
        run: |
          ROOT=$(pwd)
          ZIP="$ROOT/intiface-central-linux-${{ matrix.os }}-x64.zip"
          PACKAGE_DIR="$ROOT/release/intiface-central"

          rm -rf "$ROOT/release"
          mkdir -p "$PACKAGE_DIR"
          cp -a build/linux/x64/release/bundle/. "$PACKAGE_DIR/"
          cp linux/com.nonpolynomial.intiface_central.desktop "$PACKAGE_DIR/"
          cp linux/com.nonpolynomial.intiface_central.metainfo.xml "$PACKAGE_DIR/"
          cp linux/run_intiface_central "$PACKAGE_DIR/"

          cd "$ROOT/release"
          zip -r "$ZIP" intiface-central
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.os }}-zip
          path: ./intiface-central/intiface-central-linux-${{ matrix.os }}-x64.zip
