name: Tests
on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main]

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  unit-widget:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./intiface-central
    steps:
      - uses: actions/checkout@v4
        with:
          repository: buttplugio/buttplug_dart
          path: buttplug_dart
      - uses: actions/checkout@v4
        with:
          path: intiface-central
      - uses: dtolnay/rust-toolchain@stable
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter analyze --no-fatal-warnings --no-fatal-infos
      - run: flutter test

  integration:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: macos-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: ./intiface-central
    steps:
      - uses: actions/checkout@v4
        with:
          repository: buttplugio/buttplug_dart
          path: buttplug_dart
      - uses: actions/checkout@v4
        with:
          path: intiface-central
      - uses: dtolnay/rust-toolchain@stable
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d macos
